server:
  port: ${SERVER_PORT:8080}

execution:
  base-url: ${EXECUTION_BASE_URL:http://localhost:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/authorization}
    username: ${SPRING_DATASOURCE_USERNAME:authorization}
    password: ${SPRING_DATASOURCE_PASSWORD:authorization}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-c2gyaqqsxa2v3nig.us.auth0.com/

auth0:
  audience: https://snippet-manager
